### ISSUE TITLE
List with all TODOs

### ISSUE THREAD

**Issue by Yoshi20** [Yoshi20/PortugalSmash#1]
# Navigation
* [x] Is this logo okay?
* [x] Make sure the discord and twitter links are okay
* [x] Make sure the navigation is as you would like to have it (in web view and mobile view)

# Footer
* [x] Let me know if you would like to add or change something in the footer

# Welcome page
* [x] Let me know if the 3 big icons are okay like this
* [x] Make sure the text on the welcome page is okay like this

# Forum
* [x] Let me know which messageboards you would like to have. See https://www.smashultimate.fr/forum or https://www.germanysmash.de/forum for references

# Districts
* [x] Title?
* [x] Text?
* [x] Add at least one community page (as a reference for other community editors)

# Tournaments/Rules
* [x] Title?
* [x] Text?
* [x] Provide me with your Ruleset and Conduct

# Ranking
* [x] What would you like to display in rankings?
* [x] Provide me with PT power rankings

# Teams
* [x] Add at least one team page (as a reference for other team managers)

# Infos: General
* [x] Any info pages you would like to add or remove?
* [x] Text okay?

# Imprint
* [ ] Please provide me with an PT imprint

# Privacy policy
* [x] Please provide me with an PT privacy_policy

# Translations
* [ ] Let me know if all the English content is okay like this, so that I can give you the language file to translate everything

# Payment
* [ ] Please make a monthly SEPA payment of 20€ (My IBAN is: CH73 0900 0000 3076 1920 0; See Imprint for more info)

**Comment by AFGRocha** [comment]
What do you mean by teams?

**Comment by AFGRocha** [comment]
This is our ruleset https://i.imgur.com/GEtmZA1.jpg

**Comment by AFGRocha** [comment]
District page I think it's fine the way it is it's just that sadly tournaments usually just happen in two/three, so my fear is that " SSBU Community can be divided into 20 districs" could be misleading

**Comment by AFGRocha** [comment]
In the rankings page is it possible to have regional tabs?

So that this can be shown as well: https://twitter.com/SmashBrosPT/status/1542520804637757441

**Comment by AFGRocha** [comment]
Not sure what to do with the communities. Since our country is small, everything is done in a single discord server.

**Comment by AFGRocha** [comment]
> Not sure what to do with the communities. Since our country is small, everything is done in a single discord server.
> 
> For example Switzerland and Luxembourg also do not have a communities page. So I can easily remove/hide it, if you don't need it :) Just let me know.

Yes, that would work

**Comment by AFGRocha** [comment]
Privacy Policy: https://docs.google.com/document/d/10Wu0qVXTlX6LHBeUHdrGQVl4Q16eCQ4WGqovAYEGQOY/edit?usp=sharing
